version: "3.8"
services:
  wireadmin:
    environment:
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=raspberrypi.local

    image: shahradel/wireadmin
    container_name: wireadmin
    volumes:
      - ~/.wg-data:/data
    ports:
      - "51820:51820/udp"
      - "3000:3000/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

